'use strict';

module.exports =
  angular.module('mtos', [
    'ui.bootstrap',
    'ui.router',
    //load extra external dependencies here, e.g.:
    //'ngAnimate',
    'LocalForageModule',
    'ngCordova',
    'angularSpinner',
    //'uuid4',
    //html templates in $templateCache generated by Gulp:
    require('../../../tmp/templates').name,
    //useful directives, filters, services shared across the app
    require('../common').name,
    //example app module:
    //require('./foo').name,
    require('./screenOwnership').name,
    require('./identities').name
    //load extra app modules here, e.g.:
    //require('./frontend').name,
    //require('./admin').name
  ])
  .config(function ($stateProvider, $localForageProvider) {
    $localForageProvider.config({
      name: 'mtos' // name of the database and prefix for your data
    });
  })
  .run(require('./rootScopeController'));
